# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='profile',
        ),
        migrations.AddField(
            model_name='application',
            name='submitted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
