# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20151221_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='anything_else',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_hackathons',
            field=models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4+', b'4+')], default=b'0', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='devpost_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(choices=[(b'None', b'None'), (b'Vegetarian', b'Vegetarian'), (b'Vegan', b'Vegan'), (b'Gluten Free', b'Gluten Free')], default=b'None', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='t_shirt_size',
            field=models.CharField(choices=[(b'XS', b'XS'), (b'S', b'S'), (b'M', b'M'), (b'L', b'L'), (b'XL', b'XL')], default=b'XS', max_length=2),
        ),
    ]
