# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20151222_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='devpost_profile',
            field=models.URLField(blank=True, default=b'http://devpost.com/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_profile',
            field=models.URLField(blank=True, default=b'https://github.com/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile',
            field=models.URLField(blank=True, default=b'https://www.linkedin.com/in/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True, default=b'http://'),
        ),
    ]
