# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20151224_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(blank=True, default=b'http://', max_length=200),
        ),
    ]
