# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20151224_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='not entered', max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(choices=[(b'None', b'None'), (b'Vegetarian', b'Vegetarian'), (b'Vegan', b'Vegan'), (b'Gluten Free', b'Gluten Free'), (b'Other', b'Other')], default=b'None', max_length=15),
        ),
    ]
