# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20160104_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'Other', b'Other'), (b'Prefer not to say', b'No answer')], default=b'Male', max_length=10),
        ),
    ]
