# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='waitlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'Other', b'Other'), (b'No answer', b'Prefer not to say')], default=b'Male', max_length=10),
        ),
    ]
