# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20160316_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='can_come',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='cannot_come',
            field=models.BooleanField(default=False),
        ),
    ]
