# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20160316_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sanitized_school',
            field=models.CharField(default=b'Other', max_length=100),
        ),
    ]
