# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_application_sanitized_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='form_url',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
