# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_application_can_bring_chaperone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='can_bring_chaperone',
            field=models.NullBooleanField(default=None),
        ),
    ]
