# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20161123_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file_upload',
            field=models.FileField(upload_to=b'file_uploads/'),
        ),
    ]
