# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_remove_application_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='form_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='form_url',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
