# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20161130_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary_restrictions_other',
            field=models.CharField(default=b'None', max_length=15),
        ),
    ]
