# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20161204_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='form_url',
        ),
        migrations.AddField(
            model_name='application',
            name='form_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
