# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20161208_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cool_project',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='form_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_summer',
            field=models.TextField(blank=True),
        ),
    ]
