# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20161227_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo_form_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
