# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20170118_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
    ]
