# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20170121_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(default=b'None', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=150),
        ),
    ]
