# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 00:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20170123_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_restrictions',
            field=models.CharField(default=b'None', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message=b"Zip code must be in the format '94027'. Only five numeric digits allowed.", regex=b'\\d{5}')]),
        ),
    ]
