# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_profile_auto_accept'),
        ('application', '0028_auto_20170202_0245'),
    ]

    operations = [
    ]
