# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20170217_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='application_reviewers',
        ),
    ]
