# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_profile_application_reviewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationreview',
            name='form_ok',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='photo_form_ok',
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviewed', to='application.Profile'),
        ),
    ]
