# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0033_auto_20170220_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationreview',
            name='reviewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
