# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_applicationreview_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='application_reviewers',
        ),
    ]
